### ISSUE TITLE
OutOfMemory when I tried to upload video binary string to server

### ISSUE THREAD

**Issue by njpalmin** [nkzawa/socket.io-client.java#106]
I got the outOfMemory error when I tried to upload the binary string to server. Error is like this:

java.lang.OutOfMemoryError
            at java.lang.AbstractStringBuilder.enlargeBuffer(AbstractStringBuilder.java:94)
            at java.lang.AbstractStringBuilder.append0(AbstractStringBuilder.java:145)
            at java.lang.StringBuilder.append(StringBuilder.java:202)
            at com.github.nkzawa.socketio.parser.Parser$Encoder.encodeAsString(Parser.java:115)
            at com.github.nkzawa.socketio.parser.Parser$Encoder.encode(Parser.java:84)
            at com.github.nkzawa.socketio.client.Manager.packet(Manager.java:428)
            at com.github.nkzawa.socketio.client.Socket.packet(Socket.java:253)
            at com.github.nkzawa.socketio.client.Socket.access$1200(Socket.java:18)
            at com.github.nkzawa.socketio.client.Socket$5.run(Socket.java:190)
            at com.github.nkzawa.thread.EventThread$2.run(EventThread.java:75)
            at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
            at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
            at java.lang.Thread.run(Thread.java:841)

Here is the code 
        JSONObject obj = new JSONObject();
        try {
            obj.put("buffer", data);
            obj.put("timepoints", mVideoRecordingTimestamp.toArray());
            mSocket.emit(Constant.CMD_VIDEO_FILE, obj);
        } catch (JSONException e) {
            Log.e(TAG,"JSON failed");

        }
The data is the string which size is 9732488

Thanks!

**Comment by nkzawa** [comment]
I think the file is just too big. You have to split it to chunks and send small data little by little.

**Comment by njpalmin** [comment]
Do you know the size limitation of every chunk?

**Comment by nkzawa** [comment]
There is no specific limitation. It just depends on your environment.

Sorry but I wonder whether the cause is really the file size now. Actually, 10MB sounds not so large.
What kind of environment is it?

**Comment by njpalmin** [comment]
In Android 4.4.

**Comment by nkzawa** [comment]
https://developer.android.com/training/articles/memory.html
> Android sets a hard limit on the heap size for each app.

Sorry for the delay, but anyway I think the above restriction is the cause.

**Comment by GrifonGT** [comment]
Its problem with Socket.io.
Try to loop something like:
socket.emit("message", "a");
And check Memory Monitor
