### ISSUE TITLE
Unhandled exception thrown when the server sends a Long as Event name

### ISSUE THREAD

**Issue by oliverhausler** [nkzawa/socket.io-client.java#126]
I believe not always, but sometimes an exception is thrown during disconnect:

03-26 12:05:38.606  11633-11633/cc.closeup.android E/UnhandledException﹕ Fatal error: java.lang.Long cannot be cast to java.lang.String
    java.lang.ClassCastException: java.lang.Long cannot be cast to java.lang.String
            at com.github.nkzawa.socketio.client.Socket.onevent(Socket.java:315)
            at com.github.nkzawa.socketio.client.Socket.onpacket(Socket.java:280)
            at com.github.nkzawa.socketio.client.Socket.access$100(Socket.java:18)
            at com.github.nkzawa.socketio.client.Socket$2$2.call(Socket.java:101)
            at com.github.nkzawa.emitter.Emitter.emit(Emitter.java:117)
            at com.github.nkzawa.socketio.client.Manager.ondecoded(Manager.java:377)
            at com.github.nkzawa.socketio.client.Manager.access$1200(Manager.java:20)
            at com.github.nkzawa.socketio.client.Manager$3.call(Manager.java:351)
            at com.github.nkzawa.emitter.Emitter.emit(Emitter.java:117)
            at com.github.nkzawa.socketio.parser.Parser$Decoder.add(Parser.java:156)
            at com.github.nkzawa.socketio.client.Manager.ondata(Manager.java:369)
            at com.github.nkzawa.socketio.client.Manager.access$1000(Manager.java:20)
            at com.github.nkzawa.socketio.client.Manager$2.call(Manager.java:342)
            at com.github.nkzawa.emitter.Emitter.emit(Emitter.java:117)
            at com.github.nkzawa.engineio.client.Socket.onPacket(Socket.java:485)
            at com.github.nkzawa.engineio.client.Socket.access$900(Socket.java:29)
            at com.github.nkzawa.engineio.client.Socket$5.call(Socket.java:288)
            at com.github.nkzawa.emitter.Emitter.emit(Emitter.java:117)
            at com.github.nkzawa.engineio.client.Transport.onPacket(Transport.java:121)
            at com.github.nkzawa.engineio.client.Transport.onData(Transport.java:113)
            at com.github.nkzawa.engineio.client.transports.WebSocket.access$100(WebSocket.java:19)
            at com.github.nkzawa.engineio.client.transports.WebSocket$1$3.run(WebSocket.java:74)
            at com.github.nkzawa.thread.EventThread$2.run(EventThread.java:75)
            at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
            at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
            at java.lang.Thread.run(Thread.java:841)

**Comment by oliverhausler** [comment]
It doesn't happen during disconnect, as I first assumed. We accidentially sent a Long value (which was meant for args[0]) as the event name. This crashed your library when it tried to convert it to String, which in turn caused the disconnect. Our mistake, but you may want to catch this and throw an invalidEventNameException or something similar if it happens.

**Comment by oliverhausler** [comment]
BTW: the javascript client just ignores it

**Comment by nkzawa** [comment]
Thanks, we should handle these exceptions..

**Comment by nkzawa** [comment]
fixed by d86c2e926fb95f9fb63577b39c92bda1fac900c2

**Comment by raizal** [comment]
In my case, args length is 2
but, when I debug it, the first object is null. the object only available on second index, index = 1
