### ISSUE TITLE
App crashes after recieving `connect` event.

### ISSUE THREAD

**Issue by vikas-fueled** [nkzawa/socket.io-client.java#136]
Whenever I get event `connect` the app crashes with the following error
```
-17 18:37:57.413  26141-26287/com.fueled.whitelabel E/AndroidRuntime﹕ FATAL EXCEPTION: EventThread
    Process: com.xxxxx.whitelabel, PID: 26141
    org.java_websocket.exceptions.WebsocketNotConnectedException
            at org.java_websocket.WebSocketImpl.send(WebSocketImpl.java:566)
            at org.java_websocket.WebSocketImpl.send(WebSocketImpl.java:543)
            at org.java_websocket.client.WebSocketClient.send(WebSocketClient.java:171)
            at com.github.nkzawa.engineio.client.transports.WebSocket$2.call(WebSocket.java:114)
            at com.github.nkzawa.engineio.parser.Parser.encodePacket(Parser.java:63)
            at com.github.nkzawa.engineio.parser.Parser.encodePacket(Parser.java:42)
            at com.github.nkzawa.engineio.client.transports.WebSocket.write(WebSocket.java:110)
            at com.github.nkzawa.engineio.client.Transport$3.run(Transport.java:98)
            at com.github.nkzawa.thread.EventThread.exec(EventThread.java:50)
            at com.github.nkzawa.engineio.client.Transport.send(Transport.java:94)
            at com.github.nkzawa.engineio.client.Socket$7.call(Socket.java:320)
            at com.github.nkzawa.emitter.Emitter$OnceListener.call(Emitter.java:164)
            at com.github.nkzawa.emitter.Emitter.emit(Emitter.java:117)
            at com.github.nkzawa.engineio.client.Transport.onOpen(Transport.java:109)
            at com.github.nkzawa.engineio.client.transports.WebSocket.access$000(WebSocket.java:19)
            at com.github.nkzawa.engineio.client.transports.WebSocket$1$1.run(WebSocket.java:56)
            at com.github.nkzawa.thread.EventThread$2.run(EventThread.java:75)
            at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
            at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
            at java.lang.Thread.run(Thread.java:818)
```

I am not sending any event after connecting, but from the logs it looks like its emitting an event internally.

**Comment by vikas-fueled** [comment]
Okay this happens when I don't `disconnect` the `Socket` on termination and start app again. If I restart the device and start app then it doesn't crash on `connect` event. 
Question: Should this be handled in library?

**Comment by nkzawa** [comment]
Hmm, I don't think the library can detect the app termination. Instead, we can warn that on README.
btw, do you know why this happens?

**Comment by vikas-fueled** [comment]
I haven't been able to reproduce this issue after some changes to server implementation for last 2 days. Will investigate further.

**Comment by shuoli84** [comment]
Close this as not repro? @nkzawa @vikas-fueled
