### ISSUE TITLE
Not work with okhttp 2.4.0-RC1

### ISSUE THREAD

**Issue by tuanchauict** [nkzawa/socket.io-client.java#150]
I got exception when I use `socket.io-client.java` with `OkHttp`

    compile 'com.squareup.okhttp:okhttp:2.4.0-RC1'
    compile 'com.squareup.okhttp:okhttp-urlconnection:2.4.0-RC1'

This is the exception:

    java.lang.IllegalArgumentException: unexpected url: ws://example.ngrok.io/sstaff/?EIO=3&token=test_token&sid=qwo6keK1n_nWmFEVAAAC&transport=websocket
                at com.squareup.okhttp.Request$Builder.url(Request.java:149)
                at com.github.nkzawa.engineio.client.transports.WebSocket.doOpen(WebSocket.java:53)
                at com.github.nkzawa.engineio.client.Transport$1.run(Transport.java:76)
                at com.github.nkzawa.thread.EventThread.exec(EventThread.java:50)
                at com.github.nkzawa.engineio.client.Transport.open(Transport.java:71)
                at com.github.nkzawa.engineio.client.Socket.probe(Socket.java:459)

**Comment by nkzawa** [comment]
How did you build the library?
It requires okhttp-ws 2.3.0 which has okhttp 2.3.0 as a dependency, not 2.4.0-RC.

**Comment by tuanchauict** [comment]
Tested.
The library works well with OkHttp 2.3.0


I tested with okhttp:2.4.0-RC1, okhttp-ws:2.4.0-RC1 but it still throw the exception
