### ISSUE TITLE
 App crash onCreate() socket.io-client-0.5.0

### ISSUE THREAD

**Issue by MuhammadKamal** [nkzawa/socket.io-client.java#155]
java.lang.NoSuchFieldError: No instance field hostnameVerifier of type Ljavax/net/ssl/HostnameVerifier; in class Lcom/github/nkzawa/socketio/client/Manager$Options; or its superclasses (declaration of 'com.github.nkzawa.socketio.client.Manager$Options' appears in /data/app/com.nilecode.depremorestaurant-2/base.apk)
            at com.github.nkzawa.socketio.client.Manager.<init>(Manager.java:125)
            at com.github.nkzawa.socketio.client.IO.socket(IO.java:78)
            at com.github.nkzawa.socketio.client.IO.socket(IO.java:42)
            at com.github.nkzawa.socketio.client.IO.socket(IO.java:38)
            at com.nilecode.depremorestaurant.connection.RealtimeConnection.connectToTheServer(RealtimeConnection.java:85)
            at com.nilecode.depremorestaurant.MainActivity.onCreate(MainActivity.java:75)
            at android.app.Activity.performCreate(Activity.java:5990)
            at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1106)
            at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2278)
            at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2387)
            at android.app.ActivityThread.access$800(ActivityThread.java:151)
            at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1303)
            at android.os.Handler.dispatchMessage(Handler.java:102)
            at android.os.Looper.loop(Looper.java:135)
            at android.app.ActivityThread.main(ActivityThread.java:5254)
            at java.lang.reflect.Method.invoke(Native Method)
            at java.lang.reflect.Method.invoke(Method.java:372)
            at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:903)
            at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:698)

**Comment by nkzawa** [comment]
Do you use the latest version of engine.io-client as the dependency?

**Comment by MuhammadKamal** [comment]
Yes i did

**Comment by nkzawa** [comment]
Can check your code again? It looks this is because the Options instance has no `hostnameVerifier` field, but it does actually if you use the latest version.

**Comment by MuhammadKamal** [comment]
IO.Options opts = new IO.Options();
          opts.reconnection = true;
           opts.reconnectionDelay = 1000;
           opts.timeout = -1;
            socket = IO.socket("http://178.62.202.224:8080");
          do i miss anything?

**Comment by nkzawa** [comment]
It looks ok, but IO.Options is expected to have `hostnameVerifier` field.

```
opts.hostnameVerifier = null;
```

Can you do this without error?

**Comment by MuhammadKamal** [comment]
can't resolve symbol hostnameVerifier

**Comment by nkzawa** [comment]
So actually, I believe you are not using the latest engine.io-client.

**Comment by MuhammadKamal** [comment]
build.gradle:
compile files('libs/socket.io-client-0.5.0.jar') 
I swear that i'm using it i even tried this:
IO.setDefaultHostnameVerifier(null);
same thing.
note i didn't include okHttp jars.

**Comment by MuhammadKamal** [comment]
Sorry i didn't see that "engine.io-client" i'm using  engine.io-client. 0.4.1

**Comment by MuhammadKamal** [comment]
Can you please tell me the dependencies for the  socket.io-client-0.5.0.jar

**Comment by nkzawa** [comment]
Please see pom.xml. I recommend to use gradle to resolve dependencies.
