### ISSUE TITLE
NoClassDefFoundError OkHttpClient

### ISSUE THREAD

**Issue by MuhammadKamal** [nkzawa/socket.io-client.java#159]
compile files('libs/socket.io-client-0.5.0.jar')
    compile files('libs/engine.io-client-0.5.0.jar')
    compile files('libs/okhttp-ws-2.3.0.jar')
    compile files('libs/okio-1.3.0.jar')
    compile files('libs/okhttp-urlconnection-2.3.0.jar')

 java.lang.NoClassDefFoundError: Failed resolution of: Lcom/squareup/okhttp/OkHttpClient;
            at com.github.nkzawa.engineio.client.transports.WebSocket.doOpen(WebSocket.java:45)
            at com.github.nkzawa.engineio.client.Transport$1.run(Transport.java:76)
            at com.github.nkzawa.thread.EventThread.exec(EventThread.java:50)
            at com.github.nkzawa.engineio.client.Transport.open(Transport.java:71)
            at com.github.nkzawa.engineio.client.Socket.probe(Socket.java:459)
            at com.github.nkzawa.engineio.client.Socket.onOpen(Socket.java:472)
            at com.github.nkzawa.engineio.client.Socket.onHandshake(Socket.java:512)
            at com.github.nkzawa.engineio.client.Socket.onPacket(Socket.java:486)
            at com.github.nkzawa.engineio.client.Socket.access$900(Socket.java:30)
            at com.github.nkzawa.engineio.client.Socket$5.call(Socket.java:300)
            at com.github.nkzawa.emitter.Emitter.emit(Emitter.java:117)
            at com.github.nkzawa.engineio.client.Transport.onPacket(Transport.java:124)
            at com.github.nkzawa.engineio.client.transports.Polling.access$700(Polling.java:15)
            at com.github.nkzawa.engineio.client.transports.Polling$2.call(Polling.java:122)
            at com.github.nkzawa.engineio.parser.Parser.decodePayload(Parser.java:251)
            at com.github.nkzawa.engineio.client.transports.Polling._onData(Polling.java:132)
            at com.github.nkzawa.engineio.client.transports.Polling.onData(Polling.java:104)
            at com.github.nkzawa.engineio.client.transports.PollingXHR$5$1.run(PollingXHR.java:115)
            at com.github.nkzawa.thread.EventThread$2.run(EventThread.java:75)
            at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
            at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
            at java.lang.Thread.run(Thread.java:818)
     Caused by: java.lang.ClassNotFoundException: Didn't find class "com.squareup.okhttp.OkHttpClient" on path: DexPathList[[zip file "/data/app/com.nilecode.depremorestaurant-1/base.apk"],nativeLibraryDirectories=[/vendor/lib, /system/lib]]
            at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:56)
            at java.lang.ClassLoader.loadClass(ClassLoader.java:511)
            at java.lang.ClassLoader.loadClass(ClassLoader.java:469)
            at com.github.nkzawa.engineio.client.transports.WebSocket.doOpen(WebSocket.java:45)
            at com.github.nkzawa.engineio.client.Transport$1.run(Transport.java:76)
            at com.github.nkzawa.thread.EventThread.exec(EventThread.java:50)
            at com.github.nkzawa.engineio.client.Transport.open(Transport.java:71)
            at com.github.nkzawa.engineio.client.Socket.probe(Socket.java:459)
            at com.github.nkzawa.engineio.client.Socket.onOpen(Socket.java:472)
            at com.github.nkzawa.engineio.client.Socket.onHandshake(Socket.java:512)
            at com.github.nkzawa.engineio.client.Socket.onPacket(Socket.java:486)
            at com.github.nkzawa.engineio.client.Socket.access$900(Socket.java:30)
            at com.github.nkzawa.engineio.client.Socket$5.call(Socket.java:300)
            at com.github.nkzawa.emitter.Emitter.emit(Emitter.java:117)
            at com.github.nkzawa.engineio.client.Transport.onPacket(Transport.java:124)
            at com.github.nkzawa.engineio.client.transports.Polling.access$700(Polling.java:15)
            at com.github.nkzawa.engineio.client.transports.Polling$2.call(Polling.java:122)
            at com.github.nkzawa.engineio.parser.Parser.decodePayload(Parser.java:251)
            at com.github.nkzawa.engineio.client.transports.Polling._onData(Polling.java:132)
            at com.github.nkzawa.engineio.client.transports.Polling.onData(Polling.java:104)
            at com.github.nkzawa.engineio.client.transports.PollingXHR$5$1.run(PollingXHR.java:115)
            at com.github.nkzawa.thread.EventThread$2.run(EventThread.java:75)
            at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
            at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
            at java.lang.Thread.run(Thread.java:818)
    Suppressed: java.lang.ClassNotFoundException: com.squareup.okhttp.OkHttpClient
            at java.lang.Class.classForName(Native Method)
            at java.lang.BootClassLoader.findClass(ClassLoader.java:781)
            at java.lang.BootClassLoader.loadClass(ClassLoader.java:841)
            at java.lang.ClassLoader.loadClass(ClassLoader.java:504)
            ... 23 more

**Comment by MuhammadKamal** [comment]
okhttp-2.4.0.jar Was missing
