### ISSUE TITLE
Crash when no connection (Race Condition)

### ISSUE THREAD

**Issue by danpe** [nkzawa/socket.io-client.java#163]
Hey,
When on low signal and connectivity is not steady I'm getting the following:
```
org.java_websocket.exceptions.WebsocketNotConnectedException
       at org.java_websocket.WebSocketImpl.send(WebSocketImpl.java:566)
       at org.java_websocket.WebSocketImpl.send(WebSocketImpl.java:543)
       at org.java_websocket.client.WebSocketClient.send(WebSocketClient.java:171)
       at com.github.nkzawa.engineio.client.transports.WebSocket$2.call(WebSocket.java:114)
       at com.github.nkzawa.engineio.parser.Parser.encodePacket(Parser.java:63)
       at com.github.nkzawa.engineio.parser.Parser.encodePacket(Parser.java:42)
       at com.github.nkzawa.engineio.client.transports.WebSocket.write(WebSocket.java:110)
       at com.github.nkzawa.engineio.client.Transport$3.run(Transport.java:98)
       at com.github.nkzawa.thread.EventThread.exec(EventThread.java:50)
       at com.github.nkzawa.engineio.client.Transport.send(Transport.java:94)
       at com.github.nkzawa.engineio.client.Socket.flush(Socket.java:599)
       at com.github.nkzawa.engineio.client.Socket.sendPacket(Socket.java:684)
       at com.github.nkzawa.engineio.client.Socket.sendPacket(Socket.java:663)
       at com.github.nkzawa.engineio.client.Socket.access$1700(Socket.java:29)
       at com.github.nkzawa.engineio.client.Socket$18.run(Socket.java:643)
       at com.github.nkzawa.thread.EventThread.exec(EventThread.java:50)
       at com.github.nkzawa.engineio.client.Socket.send(Socket.java:640)
       at com.github.nkzawa.engineio.client.Socket.write(Socket.java:609)
       at com.github.nkzawa.engineio.client.Socket.write(Socket.java:605)
       at com.github.nkzawa.socketio.client.Manager$7.call(Manager.java:431)
       at com.github.nkzawa.socketio.parser.Parser$Encoder.encode(Parser.java:85)
       at com.github.nkzawa.socketio.client.Manager.packet(Manager.java:426)
       at com.github.nkzawa.socketio.client.Socket.packet(Socket.java:253)
       at com.github.nkzawa.socketio.client.Socket.access$1200(Socket.java:18)
       at com.github.nkzawa.socketio.client.Socket$5.run(Socket.java:190)
       at com.github.nkzawa.thread.EventThread$2.run(EventThread.java:75)
       at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
       at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
       at java.lang.Thread.run(Thread.java:818)
```

As I see it happens when connection is lost in the middle of sending a packets, I think socket.io client should catch the exception and add the packet/event back to the queue to ensure retransmission.

Maybe should be reported in engine.io ?

**Comment by nkzawa** [comment]
Hi, thanks for your report, but `org.java_websocket` is not used on recent versions. Please update to the latest one.

**Comment by danpe** [comment]
OH ! is OkHttp WebSocket being used instead ?
Is it new in 0.5+ ?

**Comment by nkzawa** [comment]
yep

**Comment by danpe** [comment]
Thanks, See it as closed :)
