### ISSUE TITLE
Handling Connection timeout Error

### ISSUE THREAD

**Issue by niobsiak** [nkzawa/socket.io-client.java#52]
I have a problem with an error like this one written below:

Fatal Exception: java.lang.AssertionError
java.net.SocketTimeoutException: failed to connect to host/ip port after 90000ms: isConnected failed: ETIMEDOUT (Connection timed out)

Is there any idea to handle this Exception?
Thanks

**Comment by IvanKovalchuk** [comment]
I had the same problem.
I downloaded the source and fixed it by my own.
In org/java_websocket/client/WebSocketClient.java there is interruptableRun() function (194 line).
In this function, at the line 220 I added:
catch (java.lang.AssertionError e ) {
            onWebsocketError( conn, new Exception(e.getMessage()) );
            conn.closeConnection( CloseFrame.NEVER_CONNECTED, e.getMessage() );
            return;
 }

That's all

**Comment by skleeschulte** [comment]
@IvanKovalchuk I wonder why adding this catch block solved the issue, because line 220 in WebSocketClient.java should already catch every exception:

    } catch ( /*IOException | SecurityException | UnresolvedAddressException*/Exception e ) {//

Or am I misreading the code? Is the comment in that line not just a comment?

**Comment by rom4ek** [comment]
https://github.com/skleeschulte but AssertionError isn't derived from Exception class.:)

**Comment by shuoli84** [comment]
Close this? As it related with java_websocket, which is not a dependency to this project. @nkzawa

**Comment by IvanKovalchuk** [comment]
skleeschulte, java.lang.AssertionError is not an instance of Exception. 
So we have to add another "catch"

**Comment by skleeschulte** [comment]
ok, I see

**Comment by Abubakervbase** [comment]
09-17 19:10:57.744  20629-24789/.... E/AndroidRuntime﹕ FATAL EXCEPTION: EventThread
    Process: com.oneononedevelopment.matov, PID: 20629
    java.lang.IllegalArgumentException: delay < 0: -432345566375051264
            at java.util.Timer.schedule(Timer.java:454)
            at com.github.nkzawa.socketio.client.Manager.reconnect(Manager.java:497)
            at com.github.nkzawa.socketio.client.Manager.access$2000(Manager.java:20)
            at com.github.nkzawa.socketio.client.Manager$8$1$1.call(Manager.java:519)
            at com.github.nkzawa.socketio.client.Manager$1$3.call(Manager.java:282)
            at com.github.nkzawa.emitter.Emitter.emit(Emitter.java:117)
            at com.github.nkzawa.engineio.client.Socket.onError(Socket.java:754)
            at com.github.nkzawa.engineio.client.Socket.access$800(Socket.java:29)
            at com.github.nkzawa.engineio.client.Socket$4.call(Socket.java:293)
            at com.github.nkzawa.emitter.Emitter.emit(Emitter.java:117)
            at com.github.nkzawa.engineio.client.Transport.onError(Transport.java:63)
            at com.github.nkzawa.engineio.client.transports.PollingXHR.access$100(PollingXHR.java:19)
            at com.github.nkzawa.engineio.client.transports.PollingXHR$6$1.run(PollingXHR.java:126)
            at com.github.nkzawa.thread.EventThread$2.run(EventThread.java:75)
            at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
            at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
            at java.lang.Thread.run(Thread.java:818)

I got this error after some time of connection with server.
