### ISSUE TITLE
Issue: emiting json message create ClassCastException:

### ISSUE THREAD

**Issue by startxlabsdev** [nkzawa/socket.io-client.java#98]
Hi,

I am testing socket.io-client:0.3.0 in Android. I created socket connection and emit json message seccessfully to server and again I tried a new json object for emiting to server leads crash my app.
android code snippet is 

   socket.emit("incomingUpdate", object);

  and my json object format is 

{"message":"5324_1975$5323_1975$5322_1975$5322_1974$5322_1973$5323_1973$5324_1973$\/5324_1974$\/5323_1974#U,shiv,77.0470171,28.5768689,0.0,1970-01-15 12:33:13.169,running"}

The Error Log is below.

02-02 15:48:03.633  31173-31367/com.startxlabs.onaara E/AndroidRuntime﹕ FATAL EXCEPTION: EventThread
    Process: com.startxlabs.onaara, PID: 31173
    java.lang.ClassCastException: org.json.JSONObject cannot be cast to java.lang.String
            at com.github.nkzawa.socketio.client.Socket.onevent(Socket.java:307)
            at com.github.nkzawa.socketio.client.Socket.onpacket(Socket.java:272)
            at com.github.nkzawa.socketio.client.Socket.access$100(Socket.java:18)
            at com.github.nkzawa.socketio.client.Socket$2$2.call(Socket.java:99)
            at com.github.nkzawa.emitter.Emitter.emit(Emitter.java:117)
            at com.github.nkzawa.socketio.client.Manager.ondecoded(Manager.java:347)
            at com.github.nkzawa.socketio.client.Manager.access$1300(Manager.java:19)
            at com.github.nkzawa.socketio.client.Manager$3.call(Manager.java:321)
            at com.github.nkzawa.emitter.Emitter.emit(Emitter.java:117)
            at com.github.nkzawa.socketio.parser.Parser$Decoder.add(Parser.java:156)
            at com.github.nkzawa.socketio.client.Manager.ondata(Manager.java:339)
            at com.github.nkzawa.socketio.client.Manager.access$1100(Manager.java:19)
            at com.github.nkzawa.socketio.client.Manager$2.call(Manager.java:312)
            at com.github.nkzawa.emitter.Emitter.emit(Emitter.java:117)
            at com.github.nkzawa.engineio.client.Socket.onPacket(Socket.java:482)
            at com.github.nkzawa.engineio.client.Socket.access$800(Socket.java:29)
            at com.github.nkzawa.engineio.client.Socket$5.call(Socket.java:285)
            at com.github.nkzawa.emitter.Emitter.emit(Emitter.java:117)
            at com.github.nkzawa.engineio.client.Transport.onPacket(Transport.java:121)
            at com.github.nkzawa.engineio.client.Transport.onData(Transport.java:113)
            at com.github.nkzawa.engineio.client.transports.WebSocket.access$100(WebSocket.java:19)
            at com.github.nkzawa.engineio.client.transports.WebSocket$1$3.run(WebSocket.java:74)
            at com.github.nkzawa.thread.EventThread$2.run(EventThread.java:75)
            at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
            at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
            at java.lang.Thread.run(Thread.java:818)

Please solve out this issue. Thanks.
Startxlabs

**Comment by nkzawa** [comment]
It looks this happens when you emits an event from server to client.
Can you post your server code?

**Comment by startxlabsdev** [comment]
Thanks for your reply,  I got that error when I emit event client to server.
socket.emit("incomingUpdate", object);

and my json object format is

{"message":"5324_1975$5323_1975$5322_1975$5322_1974$5322_1973$5323_1973$5324_1973$\/5324_1974$\/5323_1974#U,shiv,77.0470171,28.5768689,0.0,1970-01-15 12:33:13.169,running"}

**Comment by nkzawa** [comment]
I understand that but this log looks "server to client" to me.

**Comment by nkzawa** [comment]
Closed due to inactivity. Feel free to reopen if you still have the problem.
